= Cadre de l'histoire
aleascript@gmail.com
Version 0.1
//:doctype: book
//:sectnums:
:pdf-theme: theme.yml
:description: Jeu narratif en 3 actes
:keywords: JdR, Solo
:imagesdir: ./resources

## Le genre

....
Heroïc-Fantasy, Science-Fiction, Post-Apocalypse, Zombies & Survivants, Anges & Démons, SteamPunk, Espionnage moderne, Historique, Pulp, SuperHéros, Pirates, Fantastique, Loups-Garous & Vampires, Uchronie, Romance, Telenovelas...
....
....
....

## L'univers

....
Donjons & Dragons, Games of Thrones, Terres du Milieu, StarWars, StarTrek, SpaceOpera, Alien, Peter Pan, Contes de Grim, Guerre de 100 ans, Antiquité, Seconde Guerre Mondiale, Les Années 50 aux Etats-Unis, les années 70 en France, Asie médiévale, Afrique antique, Dystopie ...
....
....
....
....
....

## Le thème

....
Amour, Trahison, Ouverture vs Fermeture, Soi vs Autre, Harmonie vs Désordre, Tradition vs Changement, Vie vs Mort, Vérité vs Illusion, Guerre & Paix, Sauver le monde...
....
....
....
....
....

## Le ton

....
Sérieux, Sombre, Fun, Léger, Epique, Angoissant, Horrifique, Mystérieux, Poétique, Réaliste...
....
....
....
....
....

## Le pitch

....
Un pacte avec le diable, Panique au lycée, Attaque de monstres...
....
....
....
....
....
....
....
....
....

## Les restrictions

....
Pas de magie, Pas de super pouvoirs, La technologie est bannie, Pas de mort-vivants...
....
....
....
....
....
....
....

## Les précisions

....
La magie est interdite, les animaux parlent, ...
....
....
....
....
....
....
....
