= Cadre de l'histoire
aleascript@gmail.com
Version 0.1
//:doctype: book
//:sectnums:
:pdf-theme: theme.yml
:description: Fiche de cadre du jeu 3 Actes
:keywords: Impression recto verso
:imagesdir: ./resources

## Le genre

_Heroïc-Fantasy, Science-Fiction, Post-Apocalypse, Zombies & Survivants, Anges & Démons, SteamPunk, Espionnage moderne, Historique, Pulp, SuperHéros, Pirates, Fantastique, Loups-Garous & Vampires, Uchronie, Romance, Telenovelas..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
|===

## L'univers

_Donjons & Dragons, Games of Thrones, Terres du Milieu, StarWars, StarTrek, SpaceOpera, Alien, Peter Pan, Contes de Grim, Guerre de 100 ans, Antiquité, Seconde Guerre Mondiale, Les Années 50 aux Etats-Unis, les années 70 en France, Asie médiévale, Afrique antique, Dystopie ..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
|===

## Le thème

_Amour, Trahison, Ouverture vs Fermeture, Soi vs Autre, Harmonie vs Désordre, Tradition vs Changement, Vie vs Mort, Vérité vs Illusion, Guerre & Paix, Sauver le monde..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
|===

## Le ton

_Sérieux, Sombre, Fun, Léger, Epique, Angoissant, Horrifique, Mystérieux, Poétique, Réaliste..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
|===

## Le pitch

_Un pacte avec le diable, Panique au lycée, Attaque de monstres..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
__ __
__ __
__ __
|===

## Les restrictions

_Pas de magie,  Pas de super pouvoirs, La technologie est bannie, Pas de mort-vivants..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
__ __
__ __
__ __
|===


## Les précisions

_La magie est interdite, les animaux parlent, ..._

|===
a|[%hardbreaks]
__ __
__ __
__ __
__ __
__ __
__ __
|===

