= Livret du joueur
aleascript@gmail.com
Version 0.1
//:doctype: book
//:sectnums:
:pdf-theme: theme.yml
:description: Livret du joueur de 3 Actes
:keywords: Impression en livret (4 pages)
:imagesdir: ./resources

## Le cadre

_Genre / Univers / Thème / Ton / Pitch / Restrictions / Précisions..._

[%hardbreaks]
__ __
__ __
__ __
__ __
__ __
__ __


## Mes rôles et leurs liens

_Rôles / Liens / Objectifs / Enjeux..._

[%hardbreaks]
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __
__ __


## Mes décors


<<<
== Memento

_Les différences entre les actes_
[.stripes-even,cols="6,10,12,10",]
|===
| Catégorie | Acte I | Acte II | Acte III

s| Résumé | Expositions | Péripéties | Résolutions

s| Début | Le souffleur 2+^| A gauche du souffleur

s| Fin | Plus de persos sans PP | A l'heure choisie au prélude | Plus d'enjeux à résoudre

s| But | Créer des liens et distribuer les rôles | Définir des objectifs et créer des complications | Résoudre par l'explication ou la confrontation

s| Scènes
a|Scènes de liens:

* Direct
* Indirect

a|Scènes d'interaction ou de complication:

* interruption (-1 PR)
*  ralentissement (carte cachée)
* ajout (carte retournée)
a|Scènes de résolution:

* Explication
* Confrontation

s| Evolution 2+^| PP pour les personnages et PR pendant les tirages | Plus de gain de PR et PP.

s| Tirage
a| Rare mais possible en confrontation
a|
* On utilise les PP
* Si résultat défavorable, 1 carte pour 1 PR
a| On utilise les PR

s| Létalité | Réserve ou confrontation | Tous sauf max PP du joueur (-1 PR pour sauver un perso) | Tous les personnages

s| Création d'élément 2+^| -1 PR pour une nouvelle coulisse | -1 PR pour un nouveau perso

s| Voler un élément 3+^| -2PR
|===

<<<

_Résultat des tirages_
[.stripes-even,cols="5,10,10,10",options="header"]
|===
|Carte max|Résultat|Interprétation|Impact scène
s|2-10|Echec ou réussite|Par le gagnant a|
* Surenchère possible (1 carte cachée)
* Si pas de surenchère et fin de complication, la scène continue
* Sinon fin de scène
s|V,Q,K,As|Echec ou réussite ferme|Par le gagnant| Fin de scène
s|Joker|Fiasco de l'opposant (ou exploit du gagnant)|Par un joueur non impliqué| Fin de scène
|===

_Principes_

* Pensez à décrire vos rôles, à leur donner vie, à les incarner, à penser comme eux, à ressentir comme eux: que voit on ? que ressentent-ils ? que font-ils ? que disent-ils ? que pensent-ils ?
* Pensez en particulier à des petits détails qui font la différence.
* Jouez vos rôles et non ceux des autres.
* Ne vous censurez pas, ne jugez pas les autres: en effet, les rôles ne reflètent pas ce que pense le joueur qui incarne le rôle.
* Les autres joueurs ignorent ce que vous avez en tête: vous devez donc l'exposer à travers les scènes.
* Ainsi ne soyez pas gêné de ne pas tout connaitre d'un de vos rôles. N'ayez donc pas peur des blancs et acceptez que le rôle puisse fonctionner sans tout connaitre de son background.
* N'hésitez pas à questionner les joueurs sur tel ou tel point de la fiction qui attire votre attention car il vous semble intéressant, obscur ou peu plausible.
* Il est normal qu'il y ait beaucoup d'irrésolu en cours de jeu: c'est le but du jeu d'aboutir aux résolutions lors de l'acte III.
* Créez des complications à l'acte II pour obtenir des PR et ceci même si vos rôles ne sont pas concernés a priori par l'objectif du protagoniste. Pensez à ce moment là: "What could go wrong ?" pour le protagoniste et faites le advenir.

<<<

## Notes