= Playtest #2

# Présentation

Durée: 4h

## Joueurs

* Cyril
* Florian
* Nico (souffleur)
* Sylvain

## Cadre

* Genre: zombies, super-héros
* Univers: contemporain (années 2000) en France avec possibilité d'aller retour temporel via un triangle temporel
* Thème: Tradition vs Changement, Sauver le monde
* Ton: léger
* Précisions: les zombies sont des humains avec des parasites.

En gros, les humains se font parasiter et obtiennent des pouvoirs divers. En se faisant parasiter ils meurent mais sont possédés en ayant des pouvoirs ou en se prenant pour une autre personne morte depuis longtemps.

## Coulisses, Décors & Rôles:

* L'Eglise
    - Le pape
    - Archevêque Laval
    - Frère Bruno
    - Frère Jacob
* Ville de Paris
    - Président Jacques Chirac
    - George Abitbol (Chef de la police)
    - Shal-Kra (parasite anti-humain)
    - Les égouts
    - Notre-Dame
    - La Tour-Eiffel
    - Cimetière
    - Place d'Italie
    - Myfer (sans-abri)
* Les immunisés
    - Tarik Ben Chedid (Grand recteur de la mosquée)
* La Famille Martin
    - Robert (le père)
    - Isabelle (la mère)
    - Clémentine (la fille)
    - William (le fils)
    - Miro (le bébé)
    - Une cave bunkerisée

# Acte I

## Scène 1

Laval, un archeveque austère et réac, regarde sa télé et voit le pape habité par Freddie Mercury faire son coming-out. De rage il appelle le Président Jacques Chirac, lui meme aussi habité par Elvis Presley. 

## Scène 2

Le grand recteur Tarik appelle le chef de la police car des morts sortent du cimetiere. Il voit dans ces événements le retour de Shaytan. Le chef de la police finit par le croire ou en tout cas par croire qu'il se passe bel et bien quelque chose du côté du cimetière et accepte d'envoyer une patrouille de police, tout en demandant également d'envoyer une ambulance pour interner Tarik.

## Scène 3 

Les Martin sont à table et leur bébé Miro parle en prononçant des choses étranges. La mère est gaga de son bébé et ne trouve pas cela anormal. Le père a moitié saoul gueule sur tout le monde et finalement le fils William, le seul a peu près lucide, prend Miro pour l'emmener à l'hopital.

## Scène 4 

Où l'on découvre une ombre (Shal-Kâ) ayant échoué à éliminer tous les humains au Moyen-Age avec la Peste Noire, traverser un portail et arriver Place d'Italie à notre époque. Il tue un humain trop faible pour supporter la possession puis prend alors possession d'un sans-abri Myfer. La morgue emporte le cadavre et une ambulance embarque Myfer qui, même s'il a supporté la possession, ne va pas bien du tout.  

# Scène 5

Clémentine Martin rentre du lycée et passe devant le cimetière peuplé de zombies. Croyant qu'il s'agit d'un clip de Michael Jackson, elle s'approche avec d'autres badauds. Tarik se trouve déjà là et tout zombie s'en approchant tombe au sol car il est immunisé.

Il y a également un frère exalté, le frère Bruno qui voit en cela des signes divins et compte exploiter la chose. Intervient également un autre frère, Frère Jacob qui essaie de calmer les choses et embarque Frère Bruno pour se rendre à Notre-Dame.

Les forces de l'ordre arrivent avec l'ambulance envoyée par le chef de police Abitbol. Les ambulanciers n'arrivent pas à interner Tarik et finissent par tenter d'aider les diverses victimes de Tarik par son immunité fatale aux parasités.

# Acte II

## Scène 6 

Frère Bruno et Frère Jacob arrivent à Notre-Dame pour essayer de rencontrer les autorités compétentes. Une idylle semble se nouer entre eux qui ne date pas d'aujourd'hui. Tarik appelle Laval à l'aide.

## Scène 7 

Sha-Kal-Myfer prend possession des 2 ambulanciers. Arrivés à l'hopital, il massacre les infirmiers venus pour les aider. Il croise également William et Miro en poussette. William essaie de protéger Miro mais se fait frapper par Sha-Kal-Myfer. Il s'évanouit. Miro se téléporte avec William dans la cave des Martin. On découvre que Miro se fait appeler Shangra.  

## Scène 8 

Massacre au cimetière. En effet, Tarik a fait intervenir des fidèles armés et Laval a débarqué avec des skins. C'est un carnage et Laval est blessé.

## Scène 9 

Laval blessé va a Notre-Dame se soigner. Là il y croise Frère Jacob et Bruno et les prend pour des possédés ou des hérétiques vu qu'ils voient dans ce bordel une opportunité. Blessé, affaibli, humiliés par les Frères, Laval quitte les lieux en déclarant qu'il se vengera.

Frère Jacob et Bruno, démunis, décident d'en référer à la plus haute autorité: le Pape. Le Pape les invite à vivre ouvertement leur amour naissant. Les deux frères décident d'en parler plus intimement dans les égouts sous l'église.  

## Scène 10 

Le chef de la police George Abitbol monte une cellule de crise anti-terroriste vu les incidents du cimetiere. Il croit à une attaque islamiste. 

William toujours évanoui. La famille Martin finit par se réunir dans la cave. Clémentine ayant réussi à fuir le cimetiere sans encombre revient. Les Martin appellent l'hopital dont Shal-ka a pris possession et leur répond qu'il les tuera tous et qu'il sait où il se trouve. 

## Scène 11 

William voit dans son coma que Miro deviendra Miro Martin en 2030 un grand héros de la résistance anti parasites dans un futur apocalyptique où les humains se terrent.

Mais Shal-ka lors du voyage mental de William peut faire le lien avec la cave des Martin. 

## Scène 12 

Diverses tentatives pour réveiller William qui échouent. 

Shal-ka décolle du l'hopital mais se prend un essaim de pigeons envoyés par Miro dans la tronche. Il avale un pigeon et tombe au sol. 

## Scène 13 

Jacque Chirac qui se fait appelé maintenant Jack Chirock a décidé d'organiser un grand concert avec le Pape Freddie I au Champ de Mars. Il confie l'organisation et la sécurité au chef de la police George Abitbol.

## Scène 14

William finit par se réveiller et informe les autres du danger de l'arrivée imminente de Shal-ka

Il faut donc fuir mais le père est complétement saoul, William évanoui et la mère Isabelle veut a tout prix qu'ils dinent en famille avant. Ils finissent quand meme par décoller avec le vieux fusil de 12 du père et les tupperwares de poulet de la mere dans la Scenic familiale

## Scène 15

Le pape, Jack Chirock, les 2 Frères et Abitbol sont dans les égouts pas loin du Champ de Mars prêts à faire leur concert. Abitbol hésite à les trahir mais finalement décide de pas risquer sa carrière et coordonne les choses, en particulier la fanfare militaire.

## Scène 16 

Les Martin en voiture écoutent les paroles des 2 Frères. Terrifiés ils ne savent pas quoi faire et c'est là qu'enfin Isabelle arrive à les réunir autour de son poulet qu'elle avait cuisiné et emporté dans des tupperwares. Miro bouillonne car il doit se rendre au Champ de Mars affronter Shal-ka. 

# Acte III

## Scène 17

Frère Bruno fait un grand direct devant la Tour Eiffel. Exalté, il invite à l'amour et embrasse Frère Jacob devant tout le monde puis file avec Frere Jacob dans un camion de CRS pour concrétiser leur union. Le Pape Freddie I les suit.  

Shal-ka s'est fait poussé des ailes de pigeon pour se remettre et est monté en haut de la Tour Eiffel en espérant s'en servir d'émetteur pour diffuser le parasite.

Laval revient avec des ultra-orthodoxes et descend du Trocadéro prêt à en découdre. En passant devant le camion de CRS dans lequel le pape et les deux freres forniquent, il lance une grenade qui les fait exploser.  

Tarik revient également et quelques fidèles tentent de se faire exploser au niveau des piliers de la Tour Eiffel mais c'est un échec. 

Miro décide alors de se téléporter avec Tarik immunisé au sommet de la Tour Eiffel dans une boule d'énergie qui englobera aussi Shal-Ka. Du fait des pouvoirs de Tarik, Shal-ka-Myfer et Shangra-Miro meurent. Seul reste Tarik accroché bêtement à l'antenne.


# Epilogues

Abitbol a passé les menottes à Tarik et Laval. La situation revient au calme. Et Jack Chirock lance le concert. Tout le monde danse sur une musique indienne dans une ambiance Bollywood car Abitbol a mal compris le président quand celui ci lui a demandé du Rock Indé.

On voit aussi la famille Martin arriver au Champ de Mars. William invite sa mère a danser pour la consoler de la perte de Miro le héros de la famille et Clémentine danse avec son père qui titube encore.

# Débrief

Les joueurs ont vraiment apprécié cette partie très légère dans le ton. Y avait un petit côté "Preacher" pour ceux qui connaissent la série.

Cyril a proposé de jouer plutôt les cartes séquentiellement pour avoir un côté duel lors des tirages et cela a été intégré aux règles. 

On a aussi acté qu'un figurant qui perdait ne permettait de ne gagner qu'1 PR (sauf si l'impact de l'échec impactait un rôle auquel cas le joueur peut prétendre à obtenir 2 PR ou 3 PR en cas de fiasco).

On va également travailler sur une table en 9 cases pour avoir sous la main l'ensemble des "manoeuvres" possibles selon le cas où l'on se trouve: ( Acte I,II,III et protagoniste, participant, non impliqué).

On a aussi discuté d'une éventuelle règle qui permettrait de créer des inspirations lors du prélude: inspirations qui seraient ensuite cachées et tirables par un joueur qui pataugerait un peu. Pour autant cette idée n'a pas encore été intégrée car elle présente à mon gout un risque de "What the fuck" et de cheveu sur la soupe. A creuser quand même.

De plus, Cyril a fait remarquer qu'il était plus facile de jouer quand on écrivait les objectifs de ses rôles et qu'on s'y tenait. C'est effectivement un point essentiel et un focus a été mis dessus dans les règles.

On a aussi discuté que le jeu était bien un jeu de niche mais qui ouvrait le JdR à des non-initiés du fait de la simplicité des règles et du fait qu'on ait rien à préparer.